name: retail_analytics
version: "1.0.0"
profile: retail_analytics

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

models:
  retail_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    analytics:
      +materialized: table
      +schema: analytics